# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 11:57
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='\u83dc\u5355\u540d')),
                ('dir_name', models.CharField(max_length=50, verbose_name='\u76ee\u5f55\u540d')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u6587\u7ae0\u8be6\u60c5')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('category', models.CharField(default='\u535a\u5ba2', max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u522b')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
    ]
