# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=50, verbose_name='\u76ee\u5f55\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='\u83dc\u5355\u540d')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='dir_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='article',
            name='dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u76ee\u5f55\u540d'),
        ),
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Menu', verbose_name='\u83dc\u5355\u540d'),
        ),
    ]
