# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171210_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dir',
            new_name='dir_name',
        ),
    ]
