# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171210_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='dir',
            options={'verbose_name': '\u76ee\u5f55', 'verbose_name_plural': '\u76ee\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '\u83dc\u5355', 'verbose_name_plural': '\u83dc\u5355'},
        ),
    ]
