# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171210_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='menu',
            new_name='menu_name',
        ),
    ]
