# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171210_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dir',
            old_name='dir_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 12, 10, 18, 25, 30, 177754), max_length=50, verbose_name='\u6587\u7ae0\u540d'),
            preserve_default=False,
        ),
    ]
