# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20171210_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5b50\u76ee\u5f55\u540d')),
                ('next_subDirId', models.CharField(max_length=10, verbose_name='\u4e0b\u4e00\u4e2a\u5b50\u76ee\u5f55ID')),
                ('is_firstDir', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u7b2c\u4e00\u4e2a\u5b50\u76ee\u5f55')),
            ],
            options={
                'verbose_name': '\u5b50\u76ee\u5f55',
                'verbose_name_plural': '\u5b50\u76ee\u5f55',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='dir_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='article',
            name='modify_nums',
            field=models.IntegerField(default=0, verbose_name='\u66f4\u65b0\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='dir',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='dir',
            name='is_firstDir',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u7b2c\u4e00\u4e2a\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='dir',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Menu', verbose_name='\u83dc\u5355'),
        ),
        migrations.AddField(
            model_name='dir',
            name='next_dirId',
            field=models.CharField(default=0, max_length=10, verbose_name='\u4e0b\u4e00\u4e2a\u76ee\u5f55ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='article',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u8bbf\u95ee\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='subdir',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='subdir',
            name='dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u4e00\u7ea7\u76ee\u5f55'),
        ),
    ]
