# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20171219_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u76ee\u5f55\u5173\u7cfb',
                'verbose_name_plural': '\u76ee\u5f55\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='SubDirRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u5b50\u76ee\u5f55\u5173\u7cfb',
                'verbose_name_plural': '\u5b50\u76ee\u5f55\u5173\u7cfb',
            },
        ),
        migrations.RemoveField(
            model_name='dir',
            name='next_dirId',
        ),
        migrations.RemoveField(
            model_name='subdir',
            name='next_subDirId',
        ),
        migrations.AddField(
            model_name='subdirrelation',
            name='current_subir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.SubDir', verbose_name='\u5f53\u524d\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='subdirrelation',
            name='next_subDdir',
            field=models.ManyToManyField(related_name='next_subDir', to='article.SubDir', verbose_name='\u540e\u4e00\u4e2a\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='subdirrelation',
            name='pre_subDir',
            field=models.ManyToManyField(related_name='pre_subDir', to='article.SubDir', verbose_name='\u524d\u4e00\u4e2a\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='dirrelation',
            name='current_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u5f53\u524d\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='dirrelation',
            name='next_dir',
            field=models.ManyToManyField(related_name='next_dir', to='article.Dir', verbose_name='\u540e\u4e00\u4e2a\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='dirrelation',
            name='pre_dir',
            field=models.ManyToManyField(related_name='pre_dir', to='article.Dir', verbose_name='\u524d\u4e00\u4e2a\u76ee\u5f55'),
        ),
    ]
