# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20171219_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirrelation',
            name='next_dir',
        ),
        migrations.AddField(
            model_name='dirrelation',
            name='next_dir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_dir', to='article.Dir', verbose_name='\u540e\u4e00\u4e2a\u76ee\u5f55'),
        ),
        migrations.RemoveField(
            model_name='dirrelation',
            name='pre_dir',
        ),
        migrations.AddField(
            model_name='dirrelation',
            name='pre_dir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_dir', to='article.Dir', verbose_name='\u524d\u4e00\u4e2a\u76ee\u5f55'),
        ),
    ]
