# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20171219_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirrelation',
            name='current_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Menu', verbose_name='\u5f53\u524d\u83dc\u5355'),
            preserve_default=False,
        ),
    ]
