# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_dirrelation_current_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdirrelation',
            name='current_dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u5f53\u524d\u76ee\u5f55'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdirrelation',
            name='current_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Menu', verbose_name='\u5f53\u524d\u83dc\u5355'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dirrelation',
            name='current_dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u5f53\u524d\u76ee\u5f55'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdirrelation',
            name='current_subir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.SubDir', verbose_name='\u5f53\u524d\u5b50\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='subdirrelation',
            name='next_subDdir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_subDir', to='article.SubDir', verbose_name='\u540e\u4e00\u4e2a\u5b50\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='subdirrelation',
            name='pre_subDir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_subDir', to='article.SubDir', verbose_name='\u524d\u4e00\u4e2a\u5b50\u76ee\u5f55'),
        ),
    ]
