# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20171219_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdirrelation',
            old_name='current_subir',
            new_name='current_subDir',
        ),
        migrations.RenameField(
            model_name='subdirrelation',
            old_name='next_subDdir',
            new_name='next_subDir',
        ),
    ]
