# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20171219_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdir',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Menu', verbose_name='\u83dc\u5355'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subdir',
            name='dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Dir', verbose_name='\u4e00\u7ea7\u76ee\u5f55'),
            preserve_default=False,
        ),
    ]
